server:
  port: 8080

---
spring:
  # [Datasource]
  datasource:
    url: jdbc:h2:mem:test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # [h2]
  h2:
    console:
      enabled: true # H2 Database Console 접속 여부 설정
      path: /h2-console # H2 Database Console 접속 URL 설정 : localhost:8080/h2-console

  # [JPA]
  jpa:
    hibernate:
      ddl-auto: create-drop # create auto ddl script 옵션 create-drop : application 기동 시점에 Entity를 기준으로 Table Create 후 Application 종료 시점에 Drop
#      properties:
#        hibernate:
#          format_sql: true
#          use_sql_comments: true
#          show_sql: true

  # [Redis]
  redis:
    host: localhost
    port: 6379

jwt:
  signature: test-signature-key
  issuer: io.example.jwt
  subject: resource-access
  audience: client-server
  claim-key: principal
  access-token-validity-in-seconds-term: 600000 # access token의 유효 기간 : 10분
  refresh-token-validity-in-seconds-term: 1200000 # access token의 유효 기간 : 20분